import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TitleBar from "./components/title";
import DevicesContainer from "./components/DeviceBox";
import DevicesList from "./components/DevicesList";
import AddDeviceForm from "./components/AddDeviceForm";
import SignInForm from "./components/SignInForm";
import CreateUserForm from "./components/CreateUserForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TitleBar title="Welcome to ReTrain!" />
        <DevicesList /> 
        <AddDeviceForm />
        <SignInForm />
        <CreateUserForm />
        {children}
      </body>
    </html>
  );
}